####
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name" : "Horacio",
    "password" : "OHn.bferoq",
    "email" : "Horacio@fafetaxi.com"
}

###
PUT http://localhost:3000/auth/update/user/63e8321b99f850c3538a57b0
Content-Type: application/json

{
    "name" : "Horacio Gonzales",
    "password" : "OHn.bferoq",
    "email" : "Horacio@gmail.com"
}